---
  language: go
  sudo: true
  notifications:
    email: true
  go:
    - 1.x
    - tip
  services:
    - docker
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "vWxld0jctIQ13FbUB2NYebpTtGTNpd/W8H+yMx2ngAmDXl24drhZBX9LZlGiwwRF8WkryWNkIx1T5D8SckC93753qhAslecf139WtufKPjKxsrLz4ytZmh9laeWEJUpIxE3qYAuITp+naDFmv4LhVJBPvXLlwe36mXCth6mN6HVT2ScTOc3iUJuxMwJ7FUtj7aaIG923Rm3f3L/bvlWPmlplbj8EIEci+q7C6juR9Or8l9ddJ3DVJHwhIonTYhcpVsVAnykeP4RyJlInYLQ+CxBVD3z4nYGrH2LEKQYlsyK6T10HJm6gTDl31wOUS1AgNJhyAH8Wy65Zmo2N0FwfmBg11PH3GrzfajBqJFTfkr4uzknd6ZRBT8Ph0yynYrJaCxICjdu/k+F6/T3PdN4ddv5VCf/uxnF7pzXmTm7Jj/d96lelDVL9ZtJbl9IKQBZAy9xE1RuaRHjZb5nHU8M+eXlKp/VicgrbDZv5gpV2mx5L8DSZCzDiHokcl6lAykKVAhXglkj57DNsKwC/Is5GcEzmlm9frzy2OT5DmjdALragzt00bCFXpnkHm8Why0YF9jpMnMGE9jx8oU1gJOKMBet81ZNRoUp+rPFc1WuoUohKdDGKRBdDpBvHE/KTOyP1sPd8MO2DEV+EcqKfoEBdJELqXOUZeL4z+BT85znSAvI="
    file:
      - cross/grafctl-darwin-386
      - cross/grafctl-darwin-386.md5
      - cross/grafctl-darwin-amd64
      - cross/grafctl-darwin-amd64.md5
      - cross/grafctl-linux-386
      - cross/grafctl-linux-386.md5
      - cross/grafctl-linux-amd64
      - cross/grafctl-linux-amd64.md5
      - cross/grafctl-linux-arm
      - cross/grafctl-linux-arm.md5
      - cross/grafctl-linux-arm64
      - cross/grafctl-linux-arm64.md5
      - cross/grafctl-windows-386
      - cross/grafctl-windows-386.md5
      - cross/grafctl-windows-amd64
      - cross/grafctl-windows-amd64.md5
    skip_cleanup: true
    on:
      tags: true
